# Generated by Django 3.2 on 2021-04-09 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lunch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("add_time", models.DateField()),
                ("update_time", models.DateField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
