# Generated by Django 3.2 on 2021-04-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_rename_ingredients_lunch_details_lunch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lunch",
            name="details_lunch",
        ),
        migrations.AddField(
            model_name="lunch",
            name="details",
            field=models.CharField(
                default=models.CharField(max_length=100), max_length=200
            ),
        ),
    ]
