# Generated by Django 3.2 on 2021-04-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_auto_20210412_2137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lunch",
            name="details",
            field=models.CharField(default="", max_length=200),
        ),
    ]
