# Generated by Django 3.2 on 2021-04-13 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0008_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lunch",
            name="add_time",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
